### ISSUE TITLE
limiting requirements/dependencies (specifically Seaborn)

### ISSUE THREAD

**Issue by mwprestonjr** [voytekresearch/spr2022#5]
Seaborn isn't listed in requirements.txt and isn't used for anything major. However, it is imported in the following notebooks:
bycycle_02-RealData.ipynb
specparam_02-RealData.ipynb

**Comment by benderas7** [comment]
I just rewrote bycycle_02 to not depend on seaborn, and I believe someone else changed specparam_02 to not either

**Comment by mwprestonjr** [comment]
Thanks. and yes, I removed the other.
